### Nivell 1: exercicis 1, 2 i 3

In [1]:
#Importem els mòduls necessaris per fer la tasca. 
import random, math
import numpy as np
import numpy.ma as ma

#Exercici 1 
arr = np.random.randint(10, size=8)
print(arr)

print("dimensió = %d" % (arr.ndim))
print("forma = %d" % (arr.shape))

#Exercici 2
mitjana = np.mean(arr)
print("mitjana = " ,(mitjana))
print("array - mitjana = " ,(arr - mitjana))

#Exercici 3 
matriu = np.random.randint(25, size=(5,5))
v_max = matriu.max()
print(matriu)
print("valor màxim de la matriu: %d" % (v_max))

print("valors màxims dels diferents eixos:")
print(np.amax(matriu, axis = 0))
print(np.amax(matriu, axis = 1))


[2 5 3 4 2 6 5 8]
dimensió = 1
forma = 8
mitjana =  4.375
array - mitjana =  [-2.375  0.625 -1.375 -0.375 -2.375  1.625  0.625  3.625]
[[13  5 23  3  5]
 [ 3 16 18 16 17]
 [20  5 14  1 16]
 [16 20 11 17  0]
 [ 1  2 21 19  5]]
valor màxim de la matriu: 23
valors màxims dels diferents eixos:
[20 20 23 19 17]
[23 18 20 20 21]


### Nivell 2: exercici 4(Broadcasting)

In [8]:
#Exemples de broadcasting.
#Exemple 1: 2 matrius que tenen la mateixa dimensió i forma.
matriu_a = np.random.randint(10, size = (2, 2))
matriu_b = np.random.randint(50, size = (2, 2))
print("matriu 2x2:")
print(matriu_a)
print("matriu 2x2:")
print(matriu_b)
print("suma de les matrius anteriors:")
print(matriu_a + matriu_b)

#Exemple 2: el broadcasting també és possible entre 2 matrius de diferent forma si una de les dimensions és igual a 1.
mat_a = np.random.randint(25, size = (3,3,3))
mat_b = np.random.randint(25, size = (3,3,1))
print("matriu 3x3x3:")
print(mat_a)
print("matriu 3x3x1:")
print(mat_b)
print("resta de matrius de 3 dimensions on una de les dimensions de la matriu és d=1:")
print(mat_a - mat_b)

matriu 2x2:
[[0 0]
 [9 7]]
matriu 2x2:
[[20 37]
 [12 42]]
suma de les matrius anteriors:
[[20 37]
 [21 49]]
matriu 3x3x3:
[[[ 5 10 21]
  [13 21 21]
  [15  9 10]]

 [[ 9  9  9]
  [20  0  6]
  [22 10  2]]

 [[10  3 20]
  [ 6 19  1]
  [ 5  7 19]]]
matriu 3x3x1:
[[[ 5]
  [ 3]
  [ 4]]

 [[ 4]
  [24]
  [15]]

 [[ 7]
  [18]
  [ 8]]]
resta de matrius de 3 dimensions on una de les dimensions de la matriu és d=1:
[[[  0   5  16]
  [ 10  18  18]
  [ 11   5   6]]

 [[  5   5   5]
  [ -4 -24 -18]
  [  7  -5 -13]]

 [[  3  -4  13]
  [-12   1 -17]
  [ -3  -1  11]]]


### Exercicis 5, 6 i 7

In [3]:
#Exercici 5: Generem de forma aleatoria una matriu 3x3.
matriu = np.random.randint(15, size = (3, 3))
print(matriu)

#Accedim a la primera columna i la segona fila utilitzant la indexació
columna_1 = matriu[0:, 0]
fila_2 = matriu[1, 0:]
suma = columna_1 + fila_2
print("columna 1 + fila 2 =", suma)

#Exercici 6: MaskedArray
m_mask = ma.masked_array(matriu,  mask=[(a%4)==0 for a in matriu])
print(m_mask)




[[ 5 13  8]
 [ 4  0  6]
 [12  8  3]]
columna 1 + fila 2 = [ 9  4 18]
[[5 13 --]
 [-- -- 6]
 [-- -- 3]]
