### Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np
import random, math
#Cercant en la documentació he trobat aquesta llibreria amb funcions estadístiques. 
from scipy import stats

#Definim la funció que ens retornarà el resum estadístic de l'array
def resum_est(arr):
    resum = {}
    #Si l'array té més d'una dimensió retornarà un missatge d'error
    if arr.ndim > 1:
        resum = "Error: l'array té més d'una dimensió"
    #Agrupem totes les dades estadístiques en un diccionari. 
    else:
        resum.update({"mitjana": np.mean(arr)})
        resum.update({"mediana": np.median(arr)})
        resum.update({"moda": stats.mode(arr)})
        resum.update({"rang": [min(arr), max(arr)]})
        resum.update({"desviació std": np.std(arr)})
    return resum
 
arr_1 = np.random.randint((10**3), size=(10**6))
arr_2 = np.random.randint(16, size=(8, 8))
print(resum_est(arr_1))
print(resum_est(arr_2))    

{'mitjana': 499.84689, 'mediana': 500.0, 'moda': ModeResult(mode=array([506]), count=array([1098])), 'rang': [0, 999], 'desviació std': 288.539634208765}
Error: l'array té més d'una dimensió


### Exercici 2
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [16]:
#Generem un número aleatori entre 2 i 10 que determinarà la mida dels costats del quadrat
n = random.randint(2,10)
#Generem el quadrat de números aleatoris de 0 a 100
quadrat = np.random.randint(101, size=(n,n))
print(quadrat)

[[59 60 17 41 48 51]
 [15 17 19 60 77 76]
 [53 25 71 32 29  5]
 [53 72  0 69 78 47]
 [45 72  5 20 57 18]
 [52 70  3 33 88 52]]


### Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [17]:
#Primerament, definim una funció que ens retorna una llista amb 2 arrays(total per columnes i files).
def totals(taula):
    tot_col = np.sum(taula, axis = 0)
    tot_fil = np.sum(taula, axis = 1)
    totals = [tot_col, tot_fil]
    return totals

#Cridem la funció per obtenir els totals, utilitzant la matriu de l'exercici anterior
totals = totals(quadrat)
print(totals)


#Definim una funció que permet a l'usuari obtenir el valor concret d'una fila o columna mitjançant inputs
def columnaOfila(totals, n):
    col_fil = int(input("Indica un 0 si vols obtenir el valor total d'una columna o un 1 per el d'una fila: "))
    num = int(input("Indica el número d'una columna o fila(1 - %d): " % n))
    #Mitjançant la indexació d'arrays obtenim el valor total de la fila o columna triada per l'usuari.
    total = totals[col_fil][num-1]
    if col_fil == 0:
        print("valor total de la columna %d: %d" %(num, total))
    else:
        print("valor total de la fila %d: %d" % (num, total))
columnaOfila(totals,n)

[array([277, 316, 115, 255, 377, 249]), array([276, 264, 215, 319, 217, 298])]
Indica un 0 si vols obtenir el valor total d'una columna o un 1 per el d'una fila: 1
Indica el número d'una columna o fila(1 - 6): 3
valor total de la fila 3: 215


### Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

### Coeficient de Correlació de Pearson:
El coeficient de correlació mesura la relació lineal entre dues variables sent 1 la màxima correlació positiva i -1 la màxima correlació negativa entre elles. 

Per fer aquest exercici he extret part de la informació dels següents enllaços: https://stackabuse.com/calculating-pearson-correlation-coefficient-in-python-with-numpy/ , https://www.superprof.es/apuntes/escolar/matematicas/estadistica/disbidimension/covarianza.html



In [25]:
#Definim una funció que calcula la correlació entre 2 variables de forma quasi manual.
def correlacio(x, y):
    #primerament, calculem la covariància
    xy_cov = np.mean(x*y)-(np.mean(x)*np.mean(y))
    #Després calculem la desviació std per cada una de les variables
    x_sd = np.std(x)
    y_sd = np.std(y)
    #Finalment calculem el coeficient de correlació
    corr = xy_cov/(x_sd * y_sd)
    return corr

#Definim diferents variables que ens serviràn d'exemple per l'exercici
temps = np.arange(60)
y = np.random.rand(60)
print(correlacio(temps, y))

#En aquest cas tenim les notes de mates i física d'una classe
mat = np.array([2,3,4,4,5,6,6,7,7,8,10,10])
fis = np.array([1,3,2,4,4,4,6,4,6,7,9,10])
print(correlacio(mat,fis))
#La correlació és pròxima a 1 i això ens pot indicar que els alumnes que treuen
#bones notes a una assignatura també ho fan a l'altra i a la inversa. 

#El coeficient també es pot calcular de forma + eficient amb np.corrcoef() obtenint una matriu com a return.
print("matriu de correlació:")
print(np.corrcoef(mat,fis))



0.21395282996642676
0.9355071411331453
matriu de correlació:
[[1.         0.93550714]
 [0.93550714 1.        ]]
